// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRxcwgj-P_m3Kfni9Pz__CFx3pU_aps78',
    appId: '1:2559087700:web:08b4b8897057193e7dc9c1',
    messagingSenderId: '2559087700',
    projectId: 'chat-app-3f2b3',
    authDomain: 'chat-app-3f2b3.firebaseapp.com',
    storageBucket: 'chat-app-3f2b3.firebasestorage.app',
    measurementId: 'G-5HZTPKDGNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG-3K9r87psSkblokaL6l-jpwbNC4o-J4',
    appId: '1:2559087700:android:06aad62e856d1ab97dc9c1',
    messagingSenderId: '2559087700',
    projectId: 'chat-app-3f2b3',
    storageBucket: 'chat-app-3f2b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv2ElKGeH_d-0dpJH7kFh41h2K71jQ2no',
    appId: '1:2559087700:ios:317cf4cd63117f5b7dc9c1',
    messagingSenderId: '2559087700',
    projectId: 'chat-app-3f2b3',
    storageBucket: 'chat-app-3f2b3.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
